### ISSUE TITLE
searching an number (INT field)  with LIKE does not work

### ISSUE THREAD

**Issue by tom76dc** [FriendsOfCake/search#133] opened 2016-10-21 15:08 UTC
Hi,
I am new to the search plugin. I got everyting nicely configured , but i get no results with a LIKE on a numeric field (INT). When I use LIKE on a text field it works ok.

In the database i have numbers starting with 50.. , like 5088 , 5089 , 5090

When i search with like for 508* i get no results , only when ik use the exact number 5088 i get results.
When i do the same on a text field, this is no problem. Its like the % are gone , when the field is numeric

In my model
```php
    // Search Plugin 
    public function searchConfiguration()
    {
        $search = new Manager($this);
        $search->like('q', [
                'wildcardAny' => '*',
                 'field' => ['number','notes']
            ]);
       return $search;
    }
```
Is it me , or is it a bug,

regards,
Tom

**Comment by dereuromark** [comment] 2016-10-21 15:10
This seems to be duplicate of https://github.com/FriendsOfCake/search/issues/131 and the issue in core I pointed out.

**Comment by dakota** [comment] 2016-10-21 15:14
Most database servers don't support LIKE on numeric fields.

**Comment by dereuromark** [comment] 2016-10-21 15:46
So the fix proposed as core PR only works for a small subset of DBs?

**Comment by ADmad** [comment] 2016-10-21 15:57
Closing as duplicate of #131 so that discussion can be kept in one place.

**Closed by ADmad** 2016-10-21 15:57 UTC
