### ISSUE TITLE
RFC: Returning to search results after form action

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/search#80] opened 2016-04-07 09:14 UTC
**Use-case**
You are browsing a filtered set of results, and you edit a single item. The return url from the edit action should include the search params and page.

**Implementation**
This can be implemented by a developer in their add and edit actions. I think it might be nice if the plugin could provide a cleaner api for developers to use somehow. Perhaps the PrgComponent could have a method which returns the referring url?

**Sidestep**
It might just be as simple as `return $this->redirect($this->referrer())` in which case it might be worth just adding it to the documentation.

**Thoughts**
I've created this as an RFC, just to gether some other peoples thoughts on the implementation, the value of the addition, and if it's worth just updating the docs instead.

**Comment by dereuromark** [comment] 2016-04-07 10:22
I think it is better not to rely on the referrer, this can always go wrong when the form invalidates and you have to post a 2nd time it now contains this URL.
It is better to use query strings and explicitly pass them along. That's how I always did it anyway. What do you think?

**Comment by davidyell** [comment] 2016-04-07 10:37
Yeah, I had thought along similar lines. I just wondered if adding a method to the PrgComponent would be adding functionality to it which is outside its scope. Then on the flip side of the coin, adding a whole new component just for one method feels overkill.

**Comment by ADmad** [comment] 2016-04-07 12:49
Returning back to same page after editing a record is certainly nice to have. But I don't think it's directly related to this plugin. Even if you where not using the search component and just standard sorting/paging provided by paginator helper you would still want to have that feature.

So any code for ensuring that the query string is retained (or returning to referrer page) when redirecting after successful edit action doesn't belong in this plugin. It would be better suited to have it in say the Crud plugin. IIRC Crud already has the feature that if you set the `redirect` field in the form you will be redirected to that URL upon success.

Populating the field it up to you for now. As @dereuromark pointed out it's not as simple as using the referrer as it won't work in case where edit page is reloaded in case of validation error. You need a sort of "history component" which is a bit smarter than simply maintaining referrer.

**Comment by davidyell** [comment] 2016-04-07 13:33
Yeah that makes sense, so probably best just a note in the documentation then, of a 'You might also like..' 😉

**Comment by burzum** [comment] 2016-04-15 11:11
@ADmad we have a component for that, just 100 lines long, I'll ask @netstyler if we can make it open source. My only veto is the CRUD plugin, we don't use it and I wouldn't like to to use that whole plugin just to get the single component. I'm OK with not putting it not into search (even the fact I think it fits better in search than CRUD) but into another plugin, just not CRUD.

**Comment by netstyler** [comment] 2016-04-15 11:33
@burzum It is okay for me to share the code of the component 😉

**Comment by ADmad** [comment] 2016-04-15 12:31
@burzum standalone is fine

**Comment by davidyell** [comment] 2016-04-15 14:43
👍  for adding it to the search plugin

**Comment by ADmad** [comment] 2016-04-15 14:49
I won't be added to search plugin, cause returning to referrer has nothing to do with searching. It's your edit action which needs to redirect back to required location.

**Comment by ADmad** [comment] 2016-04-15 14:53
Closing as no change is required in this plugin. People can use the plugin @burzum develops in their apps as they need and we can consider including it Crud too later on.

**Closed by ADmad** 2016-04-15 14:53 UTC

**Comment by jhli** [comment] 2016-04-15 14:57
:+1: @ADmads rationale.
It has to do with the listing (sender) aka index action setting a return path as query string and given actions (edit, edit_password, hide, whatever)

**Comment by burzum** [comment] 2016-04-15 14:59
@jhli actually our component solves this by storing the query in the session. The reason for that is that we wanted persistent filters even after the user returned to the page, so that hes not losing his filters.

**Comment by ADmad** [comment] 2016-04-15 15:00
Yeah any decent solution will need to use session :)

**Comment by jhli** [comment] 2016-04-15 15:01
Meh I am not convinced about that (tabs) but its above the scope of this ticket.

**Comment by burzum** [comment] 2016-04-15 15:22
https://github.com/World-Architects/cakephp-query-param-preserver

PR's for the test and other stuff are welcome.

**Comment by davidyell** [comment] 2016-04-16 15:01
I'm disappointed @ADmad, to me this seems a perfect fit for the search plugin, and to me has everything to do with search. It's preserving the search for the user and isn't required. It's just a nice to have in the plugin and helps solve a problem which everyone will always face when implementing this plugin.

If anything, at a minimum it should be a suggest in the composer config, and included as a 'Other enhancements' in the foc/search readme.

**Comment by dereuromark** [comment] 2016-04-19 00:16
> Yeah any decent solution will need to use session :)

That is dead-wrong IMO, any decent solution will not use any session based approach, as this will always fail with more than a single tab - and that's a huge pain in the ... and a very un-userfriendly approach.
Instead the query strings should simply be appended and passed along with each URL from that page (and back) so those will always lead to the expected results inside of this tab.

I agree with @davidyell that this should be part of the search plugin here, or at least must be possible to hook in as a separate plugin shell more easily than currently suggested.

**Comment by ionas** [comment] 2016-04-19 00:19
:+1: For pointing out why sessions are the wrong approach. :-1: For saying it should be part of search.

I do agree that any breadcrumb-should easily integrate with bake-output-pagination, CRUD-pagination, search-pagination, and possibly even edit links from single views (e.g. on your user view 'template' click edit profile, then afterwards go back there etc) etc.

**Comment by ADmad** [comment] 2016-04-19 06:00
> Instead the query strings should simply be appended and passed along with each URL from that page

So if there is a add or edit action link on the page the search querystring should be passed along to that action? That's just silly. If that was done one could never use querystring for some other purpose for that action (like for e.g. using querystring to pre-fill form field on add page).

Passing on querystring only makes sense for paging and sorting links (which is done with paginator helper) not when going to other actions.

> or at least must be possible to hook in as a separate plugin functionality more easily than currently suggested.

I am all ears for that.

**Comment by dereuromark** [comment] 2016-04-19 07:25
Sry, but silly is what you proposed.
Yes of course, that's how it always has been working and how it always will be working perfectly without any cross tab contamination (I have been the victim of too many of those crappy implementations myself).
And if you are afraid of that you simply encode or even short them with an internal key of what those mean (`?s=x`) and re-apply them on the actual side either directly or internally.
The idea remains: Never use the bad session approach, always be explicit in passing stuff around.
Works TM.

**Comment by burzum** [comment] 2016-04-19 07:40
> Instead the query strings should simply be appended and passed along with each URL from that page (and back) so those will always lead to the expected results inside of this tab.

I'm going to my 1st search page, apply 3 filters, I go to my next search page for a different section and apply there 6 filters. Now you want to somehow encode both into a query param (you must do that to avoid collisions between filters) and pass that super long string to *every single URL* on the whole page? This might resolve the problem with two tabs but leads to super long and fugly to look at and to copy and paste URLs.

I agree with your concern about the session as well but it's the lesser evil for us than what you proposed.

**Comment by dereuromark** [comment] 2016-04-19 07:48
A little bit of Logic can easily resolve that.
I have done this in the past. No problem at all.

**Comment by dereuromark** [comment] 2016-04-19 07:51
Sessions are not meant to do this thing. Doing so creates sth that is broken by design already. I strongly advice against that.

**Comment by burzum** [comment] 2016-04-19 07:51
> A little bit of Logic can easily resolve that.
I have done this in the past. No problem at all.

Would you mind sharing a link to a page that does it this way? I think I've *never* seen what you've proposed in action. Also how would an URL look like for the situation I explained in my previous comment.

**Comment by dereuromark** [comment] 2016-04-19 07:56
You don't pass them everywhere but inside each scope. 
If you leave Users Controller scope completely and it is fine to reset then you don't need to lass. This way you can manage complexity with being safe

**Comment by burzum** [comment] 2016-04-19 07:59
> If you leave Users Controller scope completely and it is fine to reset then you don't need to lass.

It's *not* fine to reset them, so what now?

**Comment by dereuromark** [comment] 2016-04-19 08:02
Then you need to live with your URLs but at least they are "correct".
Geeze, whats so hard to get here? :D

What if you filter and then copy and paste the URL for someone?
That person with MY approach will see the same (expected!!!) thing, with the session based non-sense approach that person will see no filters applied, passing him the URL with specific filters is even impossible in that case (at least when coming back and having filters applied internally via session).

**Comment by ADmad** [comment] 2016-04-19 08:02
This discussion isn't going anymore, so let's put an end to it. If anyone has concrete alternate ideas make a PR.

**Comment by dereuromark** [comment] 2016-04-19 08:05
Agreed.

**Comment by burzum** [comment] 2016-04-19 08:05
> with the session based non-sense approach that person will see no filters applied, passing him the URL with specific filters is even impossible in that case

Not true. My implementation compares the set params with the ones stored in the session and uses the passed query params instead the stored ones if they don't match.

And I agree with @ADmad.
