### ISSUE TITLE
Search for ID

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfCake/search#131] opened 2016-10-09 21:02 UTC
Sometimes it is faster to search for an ID. When I use it in the 'field' => array it won´t find the ID´s

**Comment by dereuromark** [comment] 2016-10-09 21:47
I don't understand. Do you have an example with some code?

**Comment by Isengo1989** [comment] 2016-10-19 06:54
Sorry didn´t notice until now. E-Mail came in the advertising folder.

**Controller**

```
public function index()
    {
        //$cat = $this->Auth->user('category');
        $this->paginate = ['order'=> ['Articles.display_date' => 'DESC']];

        $query = $this->Articles
                ->find('search', $this->Articles->filterParams($this->request->query));


            $this->set('articles', $this->paginate($query));
            return;
    
        }

```

**Model**

```
/**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        // Add the behaviour to your table
        $this->addBehavior('Search.Search');

        // Setup search filter using search manager
        $this->searchManager()
            //->value('article_id')            
            ->add('q', 'Search.Like', [
                'before' => true,
                'after' => true,
                'mode' => 'or',
                'comparison' => 'LIKE',
                'wildcardAny' => '*',
                'wildcardOne' => '?',
                'field' => ['title','short_description','id']
            ])
            ->add('foo', 'Search.Callback', [
                'callback' => function ($query, $args, $filter) {
                    // Modify $query as required
                }
            ]);
```

**View**

```
<div class="search">
<?php
            echo $this->Form->create();
            echo '<span class="search-input">';
            echo $this->Form->input('q', ['label' => false, 'class'=>'form-control form-input','placeholder' => 'Suchbegriff']);
            echo '</span>';
            echo '<span class="search-button">';
            echo $this->Form->button('Suche', ['type' => 'submit', 'class' => 'btn btn-primary btn-m page-scroll']);
            //echo $this->Html->link('Reset', ['action' => 'index'], ['class' => 'buttonRight']);
            echo '</span>';
            echo $this->Form->end();
            ?>
</div>
```

**Comment by ADmad** [comment] 2016-10-19 06:56
Please provide the params you used and the query generated.

**Comment by Isengo1989** [comment] 2016-10-19 07:07
Not quiete sure what you mean by parameters, I guess how the request looks like:

https://www.test.de/subfolder/blog/alle-beitraege?q=Testartikel
**Works fine**

https://www.test.de/subfolder/blog/alle-beitraege?q=965342
**Doesn´t work** ( 965342 is the id in my articles table)

**Comment by Isengo1989** [comment] 2016-10-19 08:37
I added a new Search now, for a quick fix. Tho I am wondering, why I just can´t add the id field in my options.


**Added this to my ArticlesTable.php**
Changing the input field with jQuery on a checkbox called "ID?" from name="q" to name="id".

```
->add('id', 'Search.Like', [
                'field' => ['id']
```

**Comment by dereuromark** [comment] 2016-10-20 13:17
I think I know what it is, it has to do with the fact that ID fields are auto-casted to int.
I reproduced with id (numeric) and title:

The resulting SQL of any `%98%'` LIKE search for numeric fields ends up as
```
WHERE 
  (
    `TableName`.`title` like '%98%' 
    OR `TableName`.`id` like 0
  ) 
```

It should detect from the schema that this is a numeric field and then change the search type here maybe.

**Comment by dereuromark** [comment] 2016-10-20 13:23
Would this be fixed with getting https://github.com/cakephp/cakephp/pull/9162 merged? Sure looks like it.

> This is useful especially on integer types where using $query->where(['integerField LIKE' => '%' . $value . '%']) doesn't work. (The %-s are being parsed in as the input data, where instead they should be used completely separately.

**Comment by joaoahmad** [comment] 2016-11-11 21:44
I'm using the Callback filter to turn around and setting the `integer` field to `string`.
```php
$this->searchManager()
->add('q', 'Search.Callback', [
    'callback' => function ($query, $args, $filter) {
        $conditions = [
            'OR' => [
                ['id LIKE' => '%' . $args['q'] .'%'],
                ['title LIKE' => '%' . $args['q'] .'%'],
            ]
        ];
        $query->andWhere($conditions, ['id' => 'string']);
    }
])
```

**Comment by dereuromark** [comment] 2017-02-18 03:19
Would be nice if the LIKE search would also autmatically do it. It makes absolutely no sense to autocast to 0, I just needed quite a while again to figure it out and tripped over this auto cast again for a numeric column between others..

**Comment by dereuromark** [comment] 2017-02-18 04:12
PR open.

**Closed by dereuromark** 2017-02-18 04:12 UTC
Labels: enhancement
