### ISSUE TITLE
filter by belongsToMany

### ISSUE THREAD

**Issue by maxmasetti** [FriendsOfCake/search#136] opened 2016-11-12 14:32 UTC
hi,
I found this code for filtering by belongsToMany relationship. In the example code, Companies belongsToMany Sectors, in CompaniesTable you can filter by sector with:
```php
    $this->searchManager()
      ->add('sector_id', 'Search.Callback', [
        'callback' => function (Query $query, array $args, Callback $type) {
            return $query
                ->matching('Sectors', function (Query $query) use ($args) {
                    return $query
                        ->where([
                            $this->Sectors->target()->aliasField('id') => $args['sector_id']
                        ]);
                });
        }
      ]);
```
and I would like to share if not known yet.
It could be nice if a sort of shortcut could be used instead of this code, something like
```php
    $this->searchManager()
      ->add('sector_id', 'Search.BelongsToMany', [
        'matching' => 'Sectors',
        'field' => 'sector_id',
      ]);
```
thank you
max

**Comment by jippi** [comment] 2016-11-12 14:54
PR welcome :)

**Comment by maxmasetti** [comment] 2016-11-12 15:11
mm, what's "PR" (found 190 defs for it)

**Comment by tgoeminne** [comment] 2017-01-09 03:42
Hi,

have used this piece of code and it works but only when you use it once time?

How to use it when the belongstomany relation stores extra value?

products_attributes: id product_id attribute_id value

Then want to make multiple filters for this table like:

where attribute_id = 1 & value = 5
where attribute_id = 2 & value = 3

When I copy the add part so there are two callbacks, it does not work.

**Comment by maxmasetti** [comment] 2017-01-09 09:51
hi,
@tgoeminne: you probably have to customize the inner query, in particular the where clause, but I think there is only one filter field available at that level, so you can build the clause from a tokenized free text passed down. I don't know well how Cake behaves with multiple "matching" on a single many to many associated table, so the problem could be this, in your case, rather than the search plug in: solved the matching separately you can port it back in the filter, as I did for the code I add before.
Hope this helps.

**Comment by tgoeminne** [comment] 2018-08-01 12:53
->add('Color', 'Search.Callback', [
        		'callback' => function ($query, $args, $filter) {
       			return $query
        		->matching('Attributes', function ($query) use ($args) {
        			return $query
        			->where([['ProductsAttributes.eav IN' => $args['Color'],'ProductsAttributes.attribute_id' => '20']]);
        		});
        	}
        ])
        ->add('Brand', 'Search.Callback', [
            'callback' => function ($query, $args, $filter) {
            return $query
            ->matching('Attributes', function ($query) use ($args) {
                return $query
                ->where([['ProductsAttributes.eav IN' => $args['Brand'],'ProductsAttributes.attribute_id' => '22']]);
            });
            }
        ]);


INNER JOIN attributes Attributes ON ((ProductsAttributes.eav in (:c0) AND ProductsAttributes.attribute_id = :c1) AND (ProductsAttributes.eav in (:c2) AND ProductsAttributes.attribute_id = :c3) AND Attributes.id = (ProductsAttributes.attribute_id))


I have something like this. But kind of stuck there. The problem is there is not going to match any records like that of course, because if it match on one condition it is never going to match on the other condition. So probably the whole plugin is not going to work for me like that. Maybe instead of filtering from the products table I should filter starting from the products_attributes table.

The idea is to have products that can define a set of attributes a bit like magento is using. But so far I have not got it to work... Been a while since I looked at it as well..

**Comment by dereuromark** [comment] 2018-11-15 12:54
@maxmasetti Are you interested in providing a filter with your proposed finder here as PR?
Would be very welcome.

**Comment by aiphee** [comment] 2018-12-18 20:45
This works for me:

(Articles belongs to many Categories)

```php
$searchManager
			->callback('categories', [
				'callback' => function (Query $query, array $args, $manager) {
					return $query
						->matching('Categories', function (Query $query) use ($args) {
							return $query->where(['Categories.id' => $args['categories']]);
						});
				}
			]);
```

**Comment by ADmad** [comment] 2019-05-16 07:01
Closing as no one seems interested in providing a new filter for this. It's already pretty easy to achieve using the `Callback` filter anyway as shown above.

**Closed by ADmad** 2019-05-16 07:01 UTC
Labels: enhancement

**Comment by LordSimal** [comment] 2022-05-28 09:36
For everyone who is stumbling upon this issue and getting this error:
```
Search\Model\Filter\Callback::process(): Return value must be of type bool, Cake\ORM\Query returned
```

You have to return a boolean inside that callback function, not the query instance itself.
So in the above example it would be 
```
$searchManager
->callback('categories', [
	'callback' => function (Query $query, array $args, $manager) {
	            $query
			->matching('Categories', function (Query $query) use ($args) {
				return $query->where(['Categories.id' => $args['categories']]);
			});
		    return true;
	}
]);
```
